### ISSUE TITLE
How can I un-resize the image after get the segmentation result?

### ISSUE THREAD

**Issue by ShiAngWang** [Max-Manning/autoregunsupseg#3]
In train and validate, the image is loaded in 3*128*128 size, so the segmentation result has batchsize*1*128*128 shape. How can I un-resize the result, so that I can get the seg result images just like the images shown in the paper？
![image](https://user-images.githubusercontent.com/26656883/139183443-4618899b-96f9-4d1b-8ca3-f8117dc32ca7.png)

Looking forward to your reply, thanks very much!

**Comment by Max-Manning** [comment]
I'm not sure I understand your question. Are you looking for something like this?
```
result = model(x) # result has shape (B,1,H,W)
first_result = result[0,1,:,:] # first_result has shape (H,W)
```
You can then plot `first_result` with an appropriate colormap to show the segmentation result.

**Comment by ShiAngWang** [comment]
yes, but in the paper and code, the image is resized into 128x128 before transferring into the model, so the result map is 128x128 too. But in the paper, the size of result images shown seems normal, 

so that's my question, how can I unresize the result map into a normal size,   or maybe in the evaluation phrase, the author did not resize the image(is it appropriate that when the image is resized during training but not resized during inferencing)?

**Comment by Max-Manning** [comment]
If there aren't any details in the paper on this, then I have no idea.
